#!/bin/bash

# Cloudflare Deployment Setup Script
# This script helps you quickly configure environment variables for Cloudflare deployment

echo "🌐 Cloudflare Deployment Configuration"
echo "======================================"
echo ""

# Check if .env exists
if [ -f .env ]; then
  echo "⚠️  .env file already exists!"
  read -p "Do you want to overwrite it? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted. Please edit .env manually."
    exit 1
  fi
fi

# Generate session secret
echo "🔐 Generating secure session secret..."
SESSION_SECRET=$(openssl rand -base64 32)

# Ask for domain
echo ""
read -p "Enter your domain (e.g., yourdomain.com): " DOMAIN

if [ -z "$DOMAIN" ]; then
  echo "❌ Domain is required!"
  exit 1
fi

# Ask for protocol
echo ""
echo "Is your domain accessed via HTTPS? (Cloudflare usually is)"
read -p "HTTPS? (Y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]; then
  PROTOCOL="http"
  SECURE_COOKIES="false"
else
  PROTOCOL="https"
  SECURE_COOKIES="true"
fi

# Construct allowed origins
ALLOWED_ORIGINS="${PROTOCOL}://${DOMAIN}"

# Ask for subdomains
echo ""
read -p "Do you want to allow all subdomains (*.${DOMAIN})? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  ALLOWED_ORIGINS="${PROTOCOL}://*.${DOMAIN}"
fi

# Ask for additional domains
echo ""
read -p "Do you have additional domains? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Enter additional domains (comma-separated):"
  read -p "Additional domains: " ADDITIONAL
  if [ ! -z "$ADDITIONAL" ]; then
    ALLOWED_ORIGINS="${ALLOWED_ORIGINS},${ADDITIONAL}"
  fi
fi

# Create .env file
cat > .env << EOF
# Generated by setup-cloudflare.sh on $(date)

# Environment Configuration
NODE_ENV=production

# Server Configuration
PORT=3001

# Session Secret (REQUIRED)
SESSION_SECRET=${SESSION_SECRET}

# CORS Configuration (REQUIRED for Cloudflare)
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

# Cookie Configuration
SECURE_COOKIES=${SECURE_COOKIES}

# Frontend Configuration
VITE_API_URL=

# Optional: AI Provider API Keys
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GEMINI_API_KEY=AIzaSy...
EOF

echo ""
echo "✅ Configuration file created!"
echo ""
echo "📝 Summary:"
echo "  Domain: ${DOMAIN}"
echo "  Protocol: ${PROTOCOL}"
echo "  Allowed Origins: ${ALLOWED_ORIGINS}"
echo "  Secure Cookies: ${SECURE_COOKIES}"
echo ""
echo "🚀 Next steps:"
echo "  1. Review .env file if needed"
echo "  2. Run: docker-compose down"
echo "  3. Run: docker-compose build"
echo "  4. Run: docker-compose up -d"
echo ""
echo "📖 For more information, see CLOUDFLARE.md"
